/**
 * Design decisions:
 *  - Stored as a Set for O(1) lookup - important for the amount of checks done.
 *  - Words are 3–7 characters, with larger words weighted more heavily in scoring.
 *  - Kept as a relatively small set to avoid noisy results and to keep scoring fast.
 */

export const WORD_SET = new Set([
  // 3-letter words
  "ace", "act", "add", "age", "ago", "aid", "aim", "air", "all", "and",
  "ant", "any", "ape", "apt", "arc", "are", "ark", "arm", "art", "ash",
  "ask", "ate", "awe", "axe", "bad", "bag", "ban", "bar", "bat", "bay",
  "bed", "beg", "bet", "bid", "big", "bit", "boa", "bob", "bog", "bow",
  "box", "boy", "bud", "bug", "bun", "bus", "but", "buy", "cab", "can",
  "cap", "car", "cat", "cob", "cod", "cog", "cop", "cot", "cow", "cry",
  "cup", "cut", "dab", "dam", "day", "den", "dew", "did", "die", "dig",
  "dim", "dip", "doc", "dog", "dot", "dry", "dug", "dun", "duo", "ear",
  "eat", "eel", "egg", "ego", "elf", "elm", "end", "era", "eve", "ewe",
  "eye", "fad", "fan", "far", "fat", "fax", "fee", "few", "fig", "fin",
  "fit", "fix", "fly", "fog", "for", "fox", "fry", "fun", "fur", "gap",
  "gas", "gel", "gem", "get", "gig", "gin", "gnu", "god", "got", "gum",
  "gun", "gut", "guy", "gym", "had", "ham", "has", "hat", "hay", "hen",
  "her", "hid", "him", "hip", "his", "hit", "hob", "hog", "hop", "hot",
  "how", "hub", "hug", "hum", "hut", "ice", "icy", "ill", "imp", "ink",
  "inn", "ion", "ire", "ivy", "jab", "jag", "jam", "jar", "jaw", "jay",
  "jet", "jog", "jot", "joy", "jug", "jut", "keg", "key", "kid", "kin",
  "kit", "lab", "lag", "lap", "law", "lax", "lay", "lea", "led", "leg",
  "let", "lid", "lip", "lit", "log", "lot", "low", "lug", "mad", "man",
  "map", "mar", "mat", "max", "may", "men", "met", "mid", "mix", "mob",
  "mod", "mop", "mud", "mug", "nab", "nag", "nap", "net", "new", "nip",
  "nit", "nob", "nod", "nor", "not", "now", "nun", "nut", "oak", "oar",
  "odd", "off", "oil", "old", "one", "opt", "orb", "ore", "our", "out",
  "own", "pad", "pal", "pan", "pap", "par", "pat", "paw", "pay", "pea",
  "peg", "pen", "pep", "pet", "pie", "pig", "pin", "pit", "ply", "pod",
  "pop", "pot", "pow", "pro", "pry", "pub", "pug", "pun", "pup", "pus",
  "put", "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref",
  "rep", "rid", "rig", "rip", "rob", "rod", "rot", "row", "rub", "rug",
  "rum", "run", "rut", "sad", "sag", "sap", "sat", "saw", "say", "sea",
  "set", "sew", "shy", "sin", "sip", "sit", "ski", "sky", "sly", "sob",
  "sod", "son", "sow", "soy", "spa", "spy", "sty", "sub", "sue", "sum",
  "sun", "sup", "tab", "tan", "tap", "tar", "tax", "tea", "ten", "the",
  "tie", "tin", "tip", "toe", "ton", "too", "top", "toy", "try", "tub",
  "tug", "two", "urn", "use", "van", "vat", "vet", "vow", "wag", "war",
  "was", "wax", "web", "wed", "wet", "who", "why", "wig", "win", "wit",
  "woe", "wok", "won", "woo", "wow", "yam", "yap", "yaw", "yew", "you",
  "zap", "zed", "zen", "zip", "zoo",
  // 4-letter words
  "able", "ache", "acre", "aged", "also", "arch", "area", "army", "atom",
  "aunt", "auto", "avid", "away", "axes", "baby", "back", "bail", "bait",
  "bake", "bald", "ball", "band", "bane", "bang", "bank", "bare", "bark",
  "barn", "base", "bash", "bath", "bead", "beam", "bean", "bear", "beat",
  "beef", "been", "beer", "bell", "belt", "best", "bill", "bind", "bird",
  "bite", "blue", "boat", "body", "bold", "bolt", "bond", "bone", "book",
  "boom", "boot", "bore", "born", "both", "bump", "burn", "cafe", "cage",
  "cake", "call", "calm", "came", "camp", "card", "care", "cart", "case",
  "cash", "cast", "cave", "cell", "chat", "chef", "chip", "cite", "city",
  "clam", "clap", "claw", "clay", "clip", "club", "clue", "coal", "coat",
  "coil", "coin", "cold", "come", "cook", "cool", "cope", "copy", "core",
  "corn", "cost", "cozy", "crew", "crop", "crow", "cure", "curl", "damp",
  "dare", "dark", "dart", "data", "date", "dawn", "dead", "deal", "dean",
  "dear", "deck", "deed", "deep", "deer", "dell", "deny", "desk", "dial",
  "dice", "died", "diet", "dirt", "disc", "dish", "disk", "dive", "dock",
  "done", "door", "dose", "dove", "down", "drag", "draw", "drip", "drop",
  "drum", "dual", "duck", "duel", "dune", "dusk", "dust", "duty", "each",
  "earl", "earn", "ease", "east", "easy", "echo", "edge", "emit", "epic",
  "even", "ever", "evil", "exam", "face", "fact", "fade", "fail", "fair",
  "fake", "fall", "fame", "fast", "fate", "fawn", "fear", "feat", "feed",
  "feel", "feet", "fell", "felt", "fern", "fill", "film", "find", "fire",
  "firm", "fish", "fist", "five", "flag", "flat", "flaw", "fled", "flew",
  "flex", "flip", "flow", "foam", "fold", "folk", "font", "food", "foot",
  "ford", "fore", "fork", "form", "fort", "foul", "four", "free", "from",
  "fuel", "full", "fume", "fuse", "gale", "game", "gash", "gate", "gave",
  "gaze", "gear", "germ", "gift", "give", "glad", "glen", "glow", "glue",
  "goal", "goat", "gold", "golf", "gone", "good", "grab", "gray", "grew",
  "grid", "grin", "grip", "grow", "gulf", "gust", "hack", "hail", "hair",
  "half", "hall", "halt", "hand", "hang", "hard", "harm", "harp", "hate",
  "have", "hawk", "head", "heal", "heap", "hear", "heat", "heel", "held",
  "help", "herb", "hero", "high", "hill", "hint", "hire", "hold", "hole",
  "home", "hood", "hook", "hope", "horn", "hose", "host", "hour", "hull",
  "hunt", "hymn", "idea", "idle", "inch", "into", "iron", "isle", "itch",
  "item", "jade", "jail", "jazz", "jest", "join", "joke", "jump", "june",
  "jury", "just", "keen", "keep", "kelp", "kick", "kill", "kind", "king",
  "knee", "knew", "knit", "knob", "know", "lack", "lake", "lamb", "lamp",
  "land", "lane", "lark", "last", "late", "laud", "lava", "lawn", "lazy",
  "lead", "leaf", "leak", "lean", "leap", "left", "lend", "lens", "less",
  "lick", "life", "lift", "like", "lime", "line", "link", "lion", "list",
  "live", "load", "loaf", "loan", "lock", "loft", "lone", "long", "look",
  "loop", "lore", "lose", "loss", "lost", "love", "luck", "lure", "lush",
  "made", "mail", "main", "make", "male", "mall", "mane", "many", "mark",
  "mars", "mast", "mate", "math", "maze", "meal", "mean", "meat", "melt",
  "memo", "menu", "mesh", "mild", "mile", "milk", "mill", "mind", "mine",
  "mint", "miss", "mist", "mode", "mole", "moon", "more", "moss", "most",
  "moth", "move", "much", "muse", "must", "myth", "nail", "name", "navy",
  "near", "neat", "neck", "need", "news", "next", "nice", "nick", "nine",
  "node", "none", "noon", "norm", "nose", "note", "null", "oath", "obey",
  "once", "only", "open", "orca", "oval", "oven", "over", "pace", "pack",
  "page", "paid", "pain", "pair", "pale", "palm", "park", "part", "pass",
  "past", "path", "peak", "pear", "peel", "peer", "pick", "pile", "pine",
  "ping", "pipe", "plan", "play", "plea", "plod", "plot", "plow", "plum",
  "ploy", "plug", "plus", "poem", "poet", "pole", "poll", "pond", "pool",
  "poor", "pork", "port", "pose", "post", "pour", "prey", "prop", "pull",
  "pump", "pure", "push", "quit", "quiz", "race", "rack", "rage", "rail",
  "rain", "rake", "rank", "rant", "rasp", "rate", "read", "real", "reap",
  "reed", "reel", "rely", "rent", "rest", "rice", "rich", "ride", "ring",
  "riot", "rise", "risk", "road", "roam", "roar", "robe", "rock", "rode",
  "roll", "rome", "roof", "room", "rope", "rose", "ruin", "rule", "rush",
  "rust", "safe", "sage", "sail", "sale", "salt", "same", "sand", "sane",
  "save", "scan", "scar", "seam", "seed", "seem", "seen", "self", "sell",
  "send", "shed", "ship", "shoe", "shop", "shot", "show", "shut", "sick",
  "side", "sigh", "sign", "silk", "sill", "sing", "sink", "site", "size",
  "skin", "skip", "slam", "slap", "slim", "slip", "slot", "slow", "slug",
  "snap", "snow", "soak", "soap", "soar", "sock", "soft", "soil", "sold",
  "sole", "some", "song", "soon", "sore", "sort", "soul", "soup", "sour",
  "span", "spin", "spit", "spot", "spur", "star", "stay", "stem", "step",
  "stew", "stir", "stop", "stub", "stun", "such", "suit", "sure", "surf",
  "swan", "swap", "tale", "tall", "tame", "tank", "tape", "task", "team",
  "tear", "tell", "tend", "tent", "term", "test", "text", "than", "that",
  "them", "then", "they", "thin", "this", "thou", "thus", "tide", "tier",
  "tile", "till", "time", "tiny", "tire", "toad", "told", "toll", "tomb",
  "tone", "tool", "torn", "toss", "tour", "town", "tree", "trim", "trio",
  "trip", "trod", "true", "tube", "tune", "turf", "turn", "tusk", "twin",
  "type", "ugly", "undo", "unit", "upon", "urge", "used", "user", "vain",
  "vale", "vary", "vast", "veil", "vein", "very", "view", "vine", "visa",
  "void", "volt", "vote", "wade", "wage", "wake", "walk", "wall", "wand",
  "want", "ward", "warm", "warp", "wash", "wave", "weak", "weal", "wean",
  "wear", "weed", "week", "well", "went", "were", "west", "when", "whet",
  "whim", "whip", "wide", "wife", "wild", "will", "wilt", "wind", "wine",
  "wing", "wire", "wise", "wish", "with", "wolf", "wood", "wool", "word",
  "wore", "work", "worm", "wove", "wrap", "wren", "writ", "yard", "yarn",
  "year", "yell", "yoga", "yore", "your", "zero", "zest", "zinc", "zone",
  // 5-letter words
  "about", "above", "adult", "after", "again", "agent", "agree",
  "ahead", "alarm", "album", "alert", "alien", "align", "alive", "alley",
  "allow", "alone", "along", "altar", "alter", "angel", "anger", "angle",
  "angry", "anime", "annex", "antic", "anvil", "apart", "apple", "apply",
  "arena", "argue", "arise", "aroma", "arrow", "asset", "atlas", "attic",
  "audio", "audit", "avoid", "awake", "award", "aware", "awful", "baker",
  "balls", "basis", "batch", "beach", "beard", "beast", "began", "begin",
  "being", "below", "bench", "bible", "birch", "birth", "bison", "black",
  "blade", "blame", "bland", "blank", "blast", "blaze", "bleat", "bleed",
  "bless", "blind", "block", "blood", "bloom", "blown", "board", "boost",
  "bound", "boxer", "brain", "brand", "brave", "bread", "break", "breed",
  "bride", "brief", "bring", "brink", "brisk", "broad", "broke", "brook",
  "brown", "brush", "build", "built", "bunch", "burst", "buyer", "cable",
  "canal", "candy", "carry", "catch", "cause", "chain", "chair", "chalk",
  "charm", "chase", "cheap", "check", "cheek", "cheer", "chess", "chest",
  "chief", "child", "china", "choir", "chord", "chunk", "civil", "claim",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "cling",
  "clock", "close", "cloth", "cloud", "clown", "coach", "coast", "cobra",
  "color", "comic", "comma", "coral", "could", "count", "court", "cover",
  "crack", "craft", "crane", "crash", "crazy", "cream", "crest", "crime",
  "crisp", "cross", "crowd", "crown", "cruel", "crush", "curve", "cycle",
  "daily", "dairy", "dance", "deals", "debut", "delta", "depot", "depth",
  "derby", "diary", "digit", "dirty", "disco", "dizzy", "dodge", "doing",
  "donor", "doubt", "dough", "dowel", "draft", "drain", "drama", "drank",
  "drape", "drawn", "dread", "dream", "dress", "dried", "drift", "drill",
  "drink", "drive", "drone", "drove", "drown", "dryer", "dwarf", "dying",
  "eagle", "early", "earth", "eight", "elect", "elite", "ember", "empty",
  "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event",
  "every", "exact", "exist", "extra", "fable", "faced", "faith", "false",
  "fancy", "fatal", "feast", "fence", "ferry", "fever", "fiber", "field",
  "fifth", "fifty", "fight", "final", "first", "fixed", "flake", "flame",
  "flank", "flask", "flesh", "float", "flock", "flood", "floor", "floss",
  "flour", "flute", "focus", "force", "forge", "forth", "found", "frame",
  "frank", "fraud", "fresh", "front", "frost", "froze", "fruit", "fully",
  "fungi", "funny", "ghost", "given", "gland", "glass", "globe", "gloom",
  "gloss", "glove", "going", "grace", "grade", "grain", "grand", "grant",
  "grape", "grasp", "grass", "grave", "great", "green", "greet", "grief",
  "grind", "groan", "groin", "gross", "group", "grove", "grown", "guard",
  "guide", "guild", "guile", "guise", "gusto", "habit", "happy", "harsh",
  "haste", "haven", "heart", "heavy", "hence", "hinge", "hippo", "hitch",
  "hoard", "honey", "honor", "horse", "hotel", "house", "human", "humor",
  "hyena", "ideal", "image", "imply", "inbox", "index", "indie", "infer",
  "inner", "input", "inter", "intro", "issue", "ivory", "japan", "juice",
  "juicy", "karma", "karate","kayak", "knife", "knock", "known", "label",
  "labor", "lance", "large", "laser", "later", "laugh", "layer", "learn",
  "lease", "least", "ledge", "legal", "lemon", "level", "light", "limit",
  "linen", "liner", "liver", "llama", "local", "lodge", "login", "loose",
  "lotus", "lower", "loyal", "lucky", "lunar", "lyric", "magic", "major",
  "maker", "manor", "maple", "march", "marry", "match", "mayor", "media",
  "mercy", "merit", "metal", "might", "minor", "minus", "model", "money",
  "month", "moral", "motor", "mount", "mouse", "mouth", "movie", "music",
  "naive", "night", "ninja", "noble", "noise", "north", "noted", "novel",
  "nurse", "nymph", "occur", "ocean", "offer", "often", "olive", "onset",
  "orbit", "order", "other", "ought", "outdo", "outer", "oxide", "ozone",
  "paint", "panel", "panic", "paper", "party", "pasta", "patch", "pause",
  "peace", "pearl", "pedal", "penny", "perch", "phase", "phone", "photo",
  "piano", "pilot", "pinch", "pixel", "pizza", "place", "plain", "plane",
  "plant", "plate", "plaza", "plead", "pluck", "plumb", "plume", "plunk",
  "point", "poker", "polar", "poppy", "posed", "pound", "power", "press",
  "price", "pride", "prime", "print", "prior", "prize", "probe", "prose",
  "proud", "prove", "prowl", "prune", "psalm", "pulse", "pupil", "purse",
  "queen", "query", "quest", "queue", "quick", "quiet", "quite", "quota",
  "quote", "radar", "radio", "raise", "rally", "ranch", "range", "rapid",
  "ratio", "reach", "ready", "realm", "rebel", "refer", "reign", "relax",
  "remix", "reply", "rider", "ridge", "right", "ripen", "risen", "river",
  "robin", "robot", "rocky", "rouge", "rough", "round", "route", "royal",
  "rugby", "ruler", "rural", "salad", "sauce", "scale", "scene", "scope",
  "score", "scout", "scuba", "sedan", "sense", "serve", "seven", "sewn",
  "shade", "shaft", "shake", "shall", "shame", "shape", "share", "sharp",
  "sheet", "shelf", "shell", "shift", "shine", "shirt", "shock", "shore",
  "short", "shout", "sight", "since", "sixth", "sixty", "skill", "skull",
  "slate", "sleep", "slice", "slide", "slope", "smart", "smell", "smile",
  "smoke", "snake", "solar", "solid", "solve", "sorry", "south", "space",
  "spare", "spark", "spawn", "speak", "speed", "spend", "spice", "spike",
  "spine", "spoke", "spoon", "spray", "squad", "stack", "staff", "stage",
  "stain", "stair", "stake", "stale", "stand", "stark", "start", "state",
  "stave", "steal", "steam", "steel", "steep", "steer", "stick", "stiff",
  "still", "stock", "stomp", "stone", "stood", "store", "storm", "story",
  "stove", "strap", "straw", "stray", "strip", "strum", "stuck", "study",
  "stump", "style", "sugar", "suite", "super", "surge", "swamp", "sweet",
  "swept", "swift", "swipe", "sword", "swore", "sworn", "swung", "synth",
  "table", "talon", "taste", "teach", "tense", "theme", "there", "these",
  "thick", "thing", "think", "third", "those", "three", "threw", "throw",
  "thumb", "tiger", "tight", "timer", "tired", "titan", "title", "today",
  "token", "tooth", "topic", "total", "touch", "tough", "tower", "toxic",
  "track", "trade", "trail", "train", "trait", "tramp", "trash", "treat",
  "trend", "trial", "trick", "tried", "troop", "trout", "truck", "truly",
  "trump", "trunk", "trust", "truth", "tulip", "tumor", "tuned", "twirl",
  "twist", "typed", "ultra", "uncle", "under", "union", "until", "upper",
  "upset", "urban", "usage", "usual", "utter", "valid", "value", "valve",
  "vault", "vibes", "video", "vigor", "viral", "virus", "visit", "vista",
  "vital", "vivid", "vocal", "voice", "voter", "vowel", "wager", "waste",
  "watch", "water", "weave", "wedge", "weigh", "weird", "whale", "wheat",
  "where", "which", "while", "white", "whole", "whose", "witty", "woman",
  "women", "world", "worry", "worse", "worst", "worth", "would", "wound",
  "wrath", "write", "wrong", "wrote", "yacht", "yield", "young", "yours",
  "youth", "zebra",
  // 6-letter words
  "absent", "absorb", "accent", "access", "accord", "accrue", "accuse",
  "action", "active", "actual", "adjust", "admire", "admits", "advice",
  "advise", "affect", "afford", "afraid", "agenda", "agents", "agreed",
  "almost", "always", "ambush", "amount", "anchor", "annual", "answer",
  "anyone", "appear", "apples", "around", "arrive", "aspire", "assent",
  "assert", "assess", "assist", "assure", "attach", "attack", "attain",
  "attend", "battle", "beauty", "behind", "belong", "better", "beyond",
  "bottle", "bottom", "bounce", "branch", "breach", "bridge", "bright",
  "broken", "browse", "bundle", "button", "camera", "cancel", "cannot",
  "canvas", "castle", "casual", "center", "charge", "cherry", "choice",
  "choose", "chosen", "circle", "client", "closed", "cohere", "column",
  "combat", "commit", "common", "convex", "corner", "couple", "crafty",
  "create", "credit", "crispy", "custom", "damage", "danger", "daring",
  "dazzle", "define", "degree", "delete", "demand", "depend", "deploy",
  "design", "desire", "detail", "detect", "direct", "domain", "double",
  "dozens", "driven", "driver", "during", "easily", "effect", "effort",
  "enable", "engage", "engine", "enough", "entire", "entity", "escape",
  "exceed", "except", "excuse", "expand", "expect", "expert", "export",
  "extend", "factor", "fairly", "fallen", "family", "famous", "father",
  "figure", "filter", "finger", "finish", "fiscal", "flight", "follow",
  "forest", "formal", "format", "foster", "fourth", "freeze", "friend",
  "frozen", "future", "garden", "gather", "gentle", "gifted", "giving",
  "global", "gloves", "golden", "ground", "growth", "happen", "harbor",
  "hardly", "health", "height", "helper", "hidden", "highly", "honest",
  "impact", "import", "income", "indeed", "infant", "inform", "injure",
  "inside", "insist", "intake", "intend", "invest", "inward", "island",
  "joyful", "jungle", "junior", "kidney", "killer", "knight", "launch",
  "lawyer", "leader", "legacy", "lethal", "letter", "likely", "linear",
  "listen", "little", "lively", "longer", "market", "master", "matter",
  "meadow", "mental", "mentor", "mirror", "mobile", "modify", "moment",
  "mother", "motion", "muscle", "mutual", "narrow", "nation", "native",
  "nature", "nearby", "neural", "normal", "notice", "notify", "number",
  "object", "obtain", "office", "online", "option", "orange", "origin",
  "output", "palace", "parent", "passed", "patent", "pencil", "people",
  "person", "phrase", "planet", "player", "please", "pocket", "portal",
  "potato", "prefer", "pretty", "profit", "prompt", "proper", "proven",
  "public", "purple", "pursue", "radial", "random", "reason", "recent",
  "record", "reduce", "refine", "reform", "region", "relate", "remote",
  "repair", "repeat", "report", "rescue", "result", "retail", "return",
  "reveal", "review", "reward", "ribbon", "roller", "rotten", "saddle",
  "sample", "screen", "search", "season", "secret", "sector", "secure",
  "select", "series", "server", "settle", "simple", "single", "sister",
  "sketch", "social", "socket", "source", "speech", "spirit", "spread",
  "spring", "stable", "stream", "street", "strict", "strike", "strong",
  "struck", "studio", "submit", "suburb", "summer", "supply", "switch",
  "symbol", "system", "talent", "target", "tenant", "theory", "things",
  "though", "threat", "thrill", "throne", "timing", "tragic", "travel",
  "tribal", "triple", "trophy", "turtle", "tycoon", "unable", "unique",
  "united", "unlike", "update", "useful", "verify", "victim", "virtue",
  "vision", "visual", "volume", "wallet", "wander", "warmth", "wealth",
  "weight", "window", "winner", "winter", "wisdom", "wonder", "worker",
  "wounds", "yearly", "burger", "candle", "cattle", "cereal", "cherry", 
  "church", "clause", "lowers",
  // 7-letter words
  "abridge", "absence", "account", "achieve", "acquire", "address",
  "advance", "adverse", "airline", "another", "approve", "arrange",
  "article", "athlete", "attempt", "awesome", "balance", "banquet",
  "battery", "believe", "benefit", "bicycle", "billion", "blanket",
  "blossom", "cabinet", "capable", "captain", "capture", "careers",
  "certain", "chapter", "charity", "chicken", "clarity", "classic",
  "college", "comfort", "command", "compact", "company", "compass",
  "compete", "compile", "complex", "concept", "concern", "confirm",
  "connect", "consent", "contact", "contain", "content", "contest",
  "control", "convert", "correct", "council", "country", "culture",
  "cutting", "decided", "decline", "default", "deliver", "density",
  "deposit", "destiny", "develop", "digital", "disable", "disease",
  "dismiss", "display", "distant", "diverse", "doctors", "economy",
  "edition", "element", "emotion", "engaged", "examine", "example",
  "exclude", "execute", "express", "factory", "fashion", "feature",
  "fiction", "finally", "finding", "fitness", "flowers", "focused",
  "foreign", "forward", "freedom", "general", "genuine", "glacier",
  "harmony", "healthy", "history", "holiday", "however", "hundred",
  "burgers", "imagine", "improve", "include", "initial", "inspire",
  "instant", "integer", "intense", "journey", "kitchen", "knowing",
  "landing", "leading", "lasting", "lawyers", "library", "limited",
  "million", "mission", "monitor", "monster", "morning", "message",
  "nations", "natural", "network", "nothing", "noticed", "opinion",
  "organic", "outlook", "overall", "patient", "pattern", "percent",
  "perfect", "perform", "perhaps", "picture", "problem", "process",
  "product", "program", "project", "promise", "protect", "provide",
  "quality", "quarter", "reality", "receive", "recover", "replace",
  "respect", "restore", "revenue", "forward", "roofing", "service",
  "session", "setting", "shelter", "silence", "similar", "smoking",
  "someone", "special", "storage", "student", "subject", "success",
  "suggest", "support", "surface", "survive", "teacher", "thought",
  "through", "tonight", "totally", "traffic", "trained", "triumph",
  "trouble", "trusted", "uniform", "upgrade", "venture", "village",
  "vitamin", "welfare", "western", "working", "welcome", "written",
]);
